# this exact file name is required in this exact location if updates are to work
_src_path: https://github.com/iloveitaly/python-package-template.git
_commit: 8b03cd3f5196facf49d3d983f5f0e8b8cdf7a1c2
_answers_file: .copier/.copier-answers.yml
project_name: llm-sql-prompt
project_name_snake_case: llm_sql_prompt
full_name: Michael Bianco
email: mike@mikebian.co
github_username: iloveitaly
build_workflow: release_please
publish_docker_image: false
add_llm_rules: false
include_postgres: false
is_cli_tool: true
