# .github/workflows/build_and_publish.yml

name: Build and Publish to PyPI
on:
  push:
    branches:
      - main

# by default, permissions are read-only, read + write is required for git pushes
permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: uv sync
      - name: Make sure it runs
        run: uv run llm-sql-prompt --help

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6
        with:
          github-token: ${{ secrets.github_token }}
          version-file: "./pyproject.toml"
          version-path: "project.version"
          fallback-version: "0.1.0"
          output-file: "CHANGELOG.md"

      - name: Publish to PyPI
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: |
          # `gh secret set PYPI_API_TOKEN --app actions --body $PYPI_API_TOKEN`
          uv publish --token ${{ secrets.PYPI_API_TOKEN }}

      - name: Github Release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: softprops/action-gh-release@v2
        with:
          # output options: https://github.com/TriPSs/conventional-changelog-action#outputs
          body: ${{ steps.changelog.outputs.clean_changelog }}
          tag_name: ${{ steps.changelog.outputs.tag }}
